language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.2.3
sudo: false
cache: bundler

notifications:
  email:
    - tdl-commiters@googlegroups.com
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
  - mysql
before_script:
  - jdk_switcher use oraclejdk8
  - mkdir -p tmp/solr-test
before_install:  
  - sudo mkdir -p /opt/install
  - sudo wget -P /opt/install http://projects.iq.harvard.edu/files/fits/files/fits-0.8.5.zip
  - sudo unzip /opt/install/fits-0.8.5.zip -d /opt/install
  - sudo chmod +x /opt/install/fits-0.8.5/fits.sh
  - sudo cp -r /opt/install/fits-0.8.5/* /usr/local/bin/
  - sudo ln -s /usr/local/bin/fits.sh /usr/local/bin/fits
