language: ruby
rvm:
  - 2.2.3

sudo: false
cache: bundler

notifications:
  email:
    - mike.korcynski@tufts.edu
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

services:
  - redis-server
  - mysql
