language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.2.3
sudo: false
cache: bundler

notifications:
  email:
    - tdl-commiters@googlegroups.com
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
  - mysql
before_script:
  - jdk_switcher use oraclejdk8
  - mkdir -p tmp/solr-test
before_install:
  - wget http://projects.iq.harvard.edu/files/fits/files/fits-0.8.5.zip
  - unzip fits-0.8.5.zip
  - chmod +x ./fits-0.8.5/fits.sh
  - ln -s ./fits-0.8.5/fits.sh ./fits-0.8.5/fits
  - rm fits-0.8.5.zip
  - export PATH="$PATH:$(pwd)/fits-0.8.5"
