language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.2.3
sudo: false
cache: bundler

notifications:
  email:
    - mike.korcynski@tufts.edu
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
  - mysql
before_script:
  - jdk_switcher use oraclejdk8
  - mkdir -p tmp/solr-test
