# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  after_create :set_file_set_type

  def set_file_set_type
    # byebug
  end
end
